sudo: required
services:
  - docker

before_install:
  - docker build -t thanhhv317/docker-react -f Dockerfile.dev .

script:
  - echo RUN TEST
  - docker run thanhhv317/docker-react npm run test -- --coverage
